### ISSUE TITLE
New levels

### ISSUE THREAD

**Issue by GarryNL** [raspberrypilearning/sense-hat-marble-maze#7]
Hey i had a question and i hope you can help me, I have the code but iam wondering how you can implent andother level into this, like if you get to the finish it says level 2 and it starts a new level. 
And my second question is how you can use the little joystick in the sense het to move the marble.
Hope you can help me, thanks.

**Comment by lawsie** [comment]
Hi Garry. You could create multiple mazes, and then inside the check_win() function, instead of setting the game_over variable to True, you could instead show the message "You win" followed by setting the maze variable equal to the next maze you to display. To find out how to use the joystick, have a look on the Sense Hat documentation - https://pythonhosted.org/sense-hat/api/ (search for Joystick) :) Happy making!
